// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//创建和登录用户参数结构体
type UserParams struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	GroupId              string   `protobuf:"bytes,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserParams) Reset()         { *m = UserParams{} }
func (m *UserParams) String() string { return proto.CompactTextString(m) }
func (*UserParams) ProtoMessage()    {}
func (*UserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *UserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserParams.Unmarshal(m, b)
}
func (m *UserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserParams.Marshal(b, m, deterministic)
}
func (m *UserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserParams.Merge(m, src)
}
func (m *UserParams) XXX_Size() int {
	return xxx_messageInfo_UserParams.Size(m)
}
func (m *UserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UserParams.DiscardUnknown(m)
}

var xxx_messageInfo_UserParams proto.InternalMessageInfo

func (m *UserParams) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserParams) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *UserParams) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

//修改用户和删除用户
//其实如果生成uid的时候把groupId包含进去，这时候只需要一个uid即可
type UpdateParams struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateParams) Reset()         { *m = UpdateParams{} }
func (m *UpdateParams) String() string { return proto.CompactTextString(m) }
func (*UpdateParams) ProtoMessage()    {}
func (*UpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *UpdateParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateParams.Unmarshal(m, b)
}
func (m *UpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateParams.Marshal(b, m, deterministic)
}
func (m *UpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateParams.Merge(m, src)
}
func (m *UpdateParams) XXX_Size() int {
	return xxx_messageInfo_UpdateParams.Size(m)
}
func (m *UpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateParams proto.InternalMessageInfo

func (m *UpdateParams) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateParams) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

//查询用户 可以根据groupId,账号,手机号码查询
type UserPn struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	User                 []*User  `protobuf:"bytes,7,rep,name=user,proto3" json:"user,omitempty"`
	Ps                   int64    `protobuf:"varint,5,opt,name=ps,proto3" json:"ps,omitempty"`
	Pn                   int64    `protobuf:"varint,6,opt,name=pn,proto3" json:"pn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPn) Reset()         { *m = UserPn{} }
func (m *UserPn) String() string { return proto.CompactTextString(m) }
func (*UserPn) ProtoMessage()    {}
func (*UserPn) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *UserPn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPn.Unmarshal(m, b)
}
func (m *UserPn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPn.Marshal(b, m, deterministic)
}
func (m *UserPn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPn.Merge(m, src)
}
func (m *UserPn) XXX_Size() int {
	return xxx_messageInfo_UserPn.Size(m)
}
func (m *UserPn) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPn.DiscardUnknown(m)
}

var xxx_messageInfo_UserPn proto.InternalMessageInfo

func (m *UserPn) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserPn) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *UserPn) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserPn) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserPn) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserPn) GetPs() int64 {
	if m != nil {
		return m.Ps
	}
	return 0
}

func (m *UserPn) GetPn() int64 {
	if m != nil {
		return m.Pn
	}
	return 0
}

type AuthUser struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUser) Reset()         { *m = AuthUser{} }
func (m *AuthUser) String() string { return proto.CompactTextString(m) }
func (*AuthUser) ProtoMessage()    {}
func (*AuthUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{3}
}

func (m *AuthUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUser.Unmarshal(m, b)
}
func (m *AuthUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUser.Marshal(b, m, deterministic)
}
func (m *AuthUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUser.Merge(m, src)
}
func (m *AuthUser) XXX_Size() int {
	return xxx_messageInfo_AuthUser.Size(m)
}
func (m *AuthUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUser.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUser proto.InternalMessageInfo

func (m *AuthUser) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AuthUser) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//用户信息
type User struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Pwd                  string   `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Img                  string   `protobuf:"bytes,8,opt,name=img,proto3" json:"img,omitempty"`
	IsValid              int64    `protobuf:"varint,9,opt,name=isValid,proto3" json:"isValid,omitempty"`
	IsDel                int64    `protobuf:"varint,10,opt,name=isDel,proto3" json:"isDel,omitempty"`
	Create               int64    `protobuf:"varint,6,opt,name=create,proto3" json:"create,omitempty"`
	Update               int64    `protobuf:"varint,7,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *User) GetIsValid() int64 {
	if m != nil {
		return m.IsValid
	}
	return 0
}

func (m *User) GetIsDel() int64 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

func (m *User) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *User) GetUpdate() int64 {
	if m != nil {
		return m.Update
	}
	return 0
}

type UserResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	User                 []*User  `protobuf:"bytes,7,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{5}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UserResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UserParams)(nil), "admin.UserParams")
	proto.RegisterType((*UpdateParams)(nil), "admin.UpdateParams")
	proto.RegisterType((*UserPn)(nil), "admin.UserPn")
	proto.RegisterType((*AuthUser)(nil), "admin.AuthUser")
	proto.RegisterType((*User)(nil), "admin.User")
	proto.RegisterType((*UserResponse)(nil), "admin.UserResponse")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x5f, 0x71, 0x3a, 0x29, 0x90, 0x6e, 0x2b, 0xb4, 0xca, 0x85, 0xc8, 0xa7, 0x08, 0x89,
	0x04, 0x05, 0x4e, 0xdc, 0x2a, 0x55, 0x42, 0x48, 0x1c, 0x90, 0x51, 0xb8, 0x1b, 0xef, 0xc8, 0x5d,
	0x61, 0xef, 0x5a, 0xde, 0x35, 0xfc, 0x22, 0xfe, 0x18, 0x27, 0x7e, 0x06, 0xda, 0x0f, 0x97, 0xad,
	0x68, 0xd5, 0xe6, 0x36, 0x6f, 0x66, 0xde, 0xf8, 0xcd, 0x3c, 0xdb, 0xb0, 0xec, 0x07, 0xa9, 0xe5,
	0x6e, 0x54, 0x38, 0x6c, 0x6d, 0x48, 0xb2, 0x8a, 0x75, 0x5c, 0xac, 0xce, 0x7c, 0x41, 0xf3, 0x56,
	0xb9, 0x4a, 0x51, 0x02, 0x1c, 0x14, 0x0e, 0x9f, 0xab, 0xa1, 0xea, 0x14, 0xa1, 0x90, 0x57, 0x75,
	0x2d, 0x47, 0xa1, 0x69, 0xb4, 0x8e, 0x36, 0x27, 0xe5, 0x04, 0xc9, 0x12, 0x92, 0xfe, 0x27, 0xa3,
	0xb1, 0xcd, 0x9a, 0xd0, 0xf4, 0x36, 0x83, 0x1c, 0xfb, 0x8f, 0x8c, 0x26, 0xae, 0xd7, 0xc3, 0xe2,
	0x3d, 0x9c, 0x1e, 0x7a, 0x56, 0x69, 0xf4, 0x53, 0x97, 0x90, 0x8c, 0x9c, 0xf9, 0x89, 0x26, 0x0c,
	0xb9, 0xf1, 0x6d, 0xee, 0xaf, 0x08, 0x66, 0x56, 0x90, 0x38, 0x86, 0x16, 0x0a, 0x4f, 0x6e, 0x0b,
	0xbf, 0x80, 0xac, 0xbf, 0x96, 0x02, 0x69, 0x6a, 0xf3, 0x0e, 0x90, 0x97, 0x90, 0x9a, 0xf3, 0xd0,
	0x7c, 0x9d, 0x6c, 0x16, 0xfb, 0xc5, 0xd6, 0xde, 0x67, 0x6b, 0x1e, 0x5c, 0xda, 0x02, 0x79, 0x06,
	0x71, 0xaf, 0x68, 0xb6, 0x8e, 0x36, 0x49, 0x19, 0xf7, 0xca, 0x62, 0x41, 0x67, 0x1e, 0x8b, 0x62,
	0x0f, 0xf3, 0xcb, 0x51, 0x5f, 0x1b, 0xc6, 0x1d, 0x42, 0x2f, 0x20, 0xd3, 0xf2, 0x3b, 0x0a, 0x2f,
	0xd3, 0x81, 0xe2, 0x77, 0x04, 0xe9, 0x3d, 0x84, 0x40, 0x7f, 0xfc, 0x9f, 0x7e, 0xec, 0x2a, 0xde,
	0xfa, 0xbd, 0x1c, 0x98, 0xec, 0x48, 0xff, 0xd9, 0x71, 0xb3, 0x67, 0x16, 0xee, 0xb9, 0x84, 0x84,
	0x77, 0x0d, 0x9d, 0xbb, 0x3e, 0xde, 0x35, 0xe6, 0x49, 0x5c, 0x7d, 0xad, 0x5a, 0xce, 0xe8, 0x89,
	0xdd, 0x66, 0x82, 0x66, 0x02, 0x57, 0x57, 0xd8, 0x52, 0xb0, 0x79, 0x07, 0xc8, 0x0b, 0x98, 0xd5,
	0x03, 0x56, 0x1a, 0xfd, 0xf2, 0x1e, 0x99, 0xfc, 0x68, 0x4d, 0xa6, 0xb9, 0xcb, 0x3b, 0x54, 0x1c,
	0xe0, 0xd4, 0x9e, 0x11, 0x55, 0x2f, 0x85, 0x42, 0x42, 0x20, 0xad, 0x25, 0x43, 0xbf, 0xac, 0x8d,
	0x8d, 0xaa, 0x4e, 0x35, 0xd3, 0xcb, 0xd4, 0xa9, 0xe6, 0x41, 0x3f, 0xf6, 0x7f, 0x62, 0x58, 0x18,
	0xf8, 0x05, 0x87, 0x1f, 0xbc, 0x46, 0xf2, 0x06, 0xe6, 0x25, 0x36, 0x5c, 0x69, 0x1c, 0xc8, 0x59,
	0xd0, 0xee, 0x5e, 0xb9, 0xd5, 0x73, 0x9f, 0x9a, 0x64, 0x14, 0x4f, 0xc8, 0x6b, 0xc8, 0x3e, 0xc9,
	0x86, 0x8b, 0x47, 0xb6, 0xbf, 0x82, 0xd4, 0x18, 0x4c, 0xa6, 0xd2, 0xe4, 0xf6, 0x5d, 0xbd, 0x3b,
	0xc8, 0x2f, 0x19, 0xb3, 0xd6, 0x3e, 0x6e, 0xf8, 0x3b, 0x00, 0xf7, 0x85, 0x58, 0xce, 0xf9, 0xc4,
	0x09, 0x3e, 0x9a, 0x7b, 0x58, 0x57, 0xd8, 0xe2, 0x91, 0xac, 0x1d, 0xe4, 0x1f, 0x50, 0x5b, 0xca,
	0xd3, 0x50, 0x9c, 0x58, 0x9d, 0x87, 0x67, 0xbe, 0x21, 0x7c, 0x9b, 0xd9, 0x3f, 0xc3, 0xdb, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xf5, 0xd7, 0xc2, 0x47, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	//用户注册
	Register(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error)
	//用户登录
	Login(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error)
	//用户认证(有可能单独api需要鉴权访问)
	Auth(ctx context.Context, in *AuthUser, opts ...client.CallOption) (*Response, error)
	//添加用户
	AddUser(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error)
	//修改用户信息
	UpdateUser(ctx context.Context, in *UpdateParams, opts ...client.CallOption) (*Response, error)
	//删除用户(逻辑删除)
	DeleteUser(ctx context.Context, in *UpdateParams, opts ...client.CallOption) (*Response, error)
	//查询用户(可以查询所有，也可以根据分组查询)
	GetUser(ctx context.Context, in *UserPn, opts ...client.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "admin"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) Register(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Register", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Login", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Auth(ctx context.Context, in *AuthUser, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Auth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddUser(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.AddUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.UpdateUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *UpdateParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.DeleteUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserPn, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetUser", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	//用户注册
	Register(context.Context, *UserParams, *Response) error
	//用户登录
	Login(context.Context, *UserParams, *Response) error
	//用户认证(有可能单独api需要鉴权访问)
	Auth(context.Context, *AuthUser, *Response) error
	//添加用户
	AddUser(context.Context, *UserParams, *Response) error
	//修改用户信息
	UpdateUser(context.Context, *UpdateParams, *Response) error
	//删除用户(逻辑删除)
	DeleteUser(context.Context, *UpdateParams, *Response) error
	//查询用户(可以查询所有，也可以根据分组查询)
	GetUser(context.Context, *UserPn, *UserResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) Register(ctx context.Context, in *UserParams, out *Response) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *UserService) Login(ctx context.Context, in *UserParams, out *Response) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *UserService) Auth(ctx context.Context, in *AuthUser, out *Response) error {
	return h.UserServiceHandler.Auth(ctx, in, out)
}

func (h *UserService) AddUser(ctx context.Context, in *UserParams, out *Response) error {
	return h.UserServiceHandler.AddUser(ctx, in, out)
}

func (h *UserService) UpdateUser(ctx context.Context, in *UpdateParams, out *Response) error {
	return h.UserServiceHandler.UpdateUser(ctx, in, out)
}

func (h *UserService) DeleteUser(ctx context.Context, in *UpdateParams, out *Response) error {
	return h.UserServiceHandler.DeleteUser(ctx, in, out)
}

func (h *UserService) GetUser(ctx context.Context, in *UserPn, out *UserResponse) error {
	return h.UserServiceHandler.GetUser(ctx, in, out)
}
