// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/per.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PerParams struct {
	Pid                  string   `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerParams) Reset()         { *m = PerParams{} }
func (m *PerParams) String() string { return proto.CompactTextString(m) }
func (*PerParams) ProtoMessage()    {}
func (*PerParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b00dd8d68daa3f, []int{0}
}

func (m *PerParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerParams.Unmarshal(m, b)
}
func (m *PerParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerParams.Marshal(b, m, deterministic)
}
func (m *PerParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerParams.Merge(m, src)
}
func (m *PerParams) XXX_Size() int {
	return xxx_messageInfo_PerParams.Size(m)
}
func (m *PerParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PerParams.DiscardUnknown(m)
}

var xxx_messageInfo_PerParams proto.InternalMessageInfo

func (m *PerParams) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PerParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PerParams) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

//这里定义的好好想想，是针对api还是针对所有的东西包括目录
type Per struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Create               int64    `protobuf:"varint,4,opt,name=create,proto3" json:"create,omitempty"`
	Update               int64    `protobuf:"varint,5,opt,name=update,proto3" json:"update,omitempty"`
	IsValid              int64    `protobuf:"varint,6,opt,name=isValid,proto3" json:"isValid,omitempty"`
	IsDel                int64    `protobuf:"varint,7,opt,name=isDel,proto3" json:"isDel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Per) Reset()         { *m = Per{} }
func (m *Per) String() string { return proto.CompactTextString(m) }
func (*Per) ProtoMessage()    {}
func (*Per) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b00dd8d68daa3f, []int{1}
}

func (m *Per) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Per.Unmarshal(m, b)
}
func (m *Per) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Per.Marshal(b, m, deterministic)
}
func (m *Per) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Per.Merge(m, src)
}
func (m *Per) XXX_Size() int {
	return xxx_messageInfo_Per.Size(m)
}
func (m *Per) XXX_DiscardUnknown() {
	xxx_messageInfo_Per.DiscardUnknown(m)
}

var xxx_messageInfo_Per proto.InternalMessageInfo

func (m *Per) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Per) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Per) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Per) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *Per) GetUpdate() int64 {
	if m != nil {
		return m.Update
	}
	return 0
}

func (m *Per) GetIsValid() int64 {
	if m != nil {
		return m.IsValid
	}
	return 0
}

func (m *Per) GetIsDel() int64 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

//这里返回结果应该是一个Role类型
type PerPn struct {
	Pn                   int64    `protobuf:"varint,1,opt,name=pn,proto3" json:"pn,omitempty"`
	Ps                   int64    `protobuf:"varint,2,opt,name=ps,proto3" json:"ps,omitempty"`
	Per                  []*Per   `protobuf:"bytes,3,rep,name=per,proto3" json:"per,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerPn) Reset()         { *m = PerPn{} }
func (m *PerPn) String() string { return proto.CompactTextString(m) }
func (*PerPn) ProtoMessage()    {}
func (*PerPn) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b00dd8d68daa3f, []int{2}
}

func (m *PerPn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerPn.Unmarshal(m, b)
}
func (m *PerPn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerPn.Marshal(b, m, deterministic)
}
func (m *PerPn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerPn.Merge(m, src)
}
func (m *PerPn) XXX_Size() int {
	return xxx_messageInfo_PerPn.Size(m)
}
func (m *PerPn) XXX_DiscardUnknown() {
	xxx_messageInfo_PerPn.DiscardUnknown(m)
}

var xxx_messageInfo_PerPn proto.InternalMessageInfo

func (m *PerPn) GetPn() int64 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *PerPn) GetPs() int64 {
	if m != nil {
		return m.Ps
	}
	return 0
}

func (m *PerPn) GetPer() []*Per {
	if m != nil {
		return m.Per
	}
	return nil
}

func init() {
	proto.RegisterType((*PerParams)(nil), "admin.PerParams")
	proto.RegisterType((*Per)(nil), "admin.Per")
	proto.RegisterType((*PerPn)(nil), "admin.PerPn")
}

func init() { proto.RegisterFile("proto/per.proto", fileDescriptor_02b00dd8d68daa3f) }

var fileDescriptor_02b00dd8d68daa3f = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x4d, 0xd3, 0xdd, 0xb2, 0xa3, 0x58, 0x0d, 0x22, 0xa1, 0x78, 0x28, 0x7b, 0xaa, 0x07,
	0x6b, 0xa9, 0x4f, 0x20, 0x54, 0x44, 0xbc, 0x2c, 0x2b, 0x7a, 0x8f, 0xcd, 0x20, 0x81, 0x6d, 0x36,
	0x24, 0x5b, 0xdf, 0xc8, 0x97, 0xf1, 0xa9, 0x24, 0x93, 0xd6, 0xf6, 0xa0, 0xd0, 0xdb, 0xfc, 0x5f,
	0xfe, 0xfc, 0x99, 0x19, 0x02, 0x43, 0xe7, 0xdb, 0xae, 0xbd, 0x75, 0xe8, 0xa7, 0x54, 0x89, 0x4c,
	0xe9, 0x95, 0xb1, 0xa3, 0xf3, 0xc4, 0xd7, 0x9d, 0x69, 0x42, 0x3a, 0x29, 0x9f, 0xa1, 0xa8, 0xd0,
	0x57, 0xca, 0xab, 0x55, 0x10, 0x67, 0xc0, 0x9d, 0xd1, 0x92, 0x8f, 0xd9, 0xa4, 0xa8, 0x63, 0x29,
	0x04, 0xf4, 0xad, 0x5a, 0xa1, 0x64, 0x84, 0xa8, 0x16, 0x12, 0x06, 0x1f, 0xbe, 0x5d, 0xbb, 0x27,
	0x2d, 0x7b, 0x84, 0xb7, 0xb2, 0xfc, 0x62, 0xc0, 0x2b, 0xf4, 0xdb, 0x1c, 0xb6, 0xcb, 0xf9, 0xf7,
	0xce, 0xef, 0x0b, 0x7c, 0xef, 0x85, 0x4b, 0xc8, 0x97, 0x1e, 0x55, 0x87, 0xb2, 0x3f, 0x66, 0x13,
	0x5e, 0x6f, 0x54, 0xe4, 0x6b, 0xa7, 0x23, 0xcf, 0x12, 0x4f, 0x2a, 0xa6, 0x9b, 0xf0, 0xa6, 0x1a,
	0xa3, 0x65, 0x4e, 0x07, 0x5b, 0x29, 0x2e, 0x20, 0x33, 0x61, 0x81, 0x8d, 0x1c, 0x10, 0x4f, 0xa2,
	0x7c, 0x80, 0x2c, 0x0e, 0x6d, 0xc5, 0x29, 0xf4, 0x9c, 0xa5, 0x3e, 0x79, 0xdd, 0x73, 0x49, 0x07,
	0xea, 0x30, 0xea, 0x20, 0xae, 0x80, 0x3b, 0xf4, 0x92, 0x8f, 0xf9, 0xe4, 0x78, 0x0e, 0x53, 0xda,
	0xe2, 0xb4, 0x42, 0x5f, 0x47, 0x3c, 0xff, 0x66, 0x00, 0x15, 0xfa, 0x17, 0xf4, 0x9f, 0x66, 0x89,
	0xe2, 0x06, 0xf2, 0x7b, 0xad, 0x69, 0xfe, 0x9d, 0x33, 0x6d, 0x76, 0x34, 0xdc, 0x90, 0x1a, 0x83,
	0x6b, 0x6d, 0xc0, 0xf2, 0x48, 0x5c, 0x43, 0xfe, 0x88, 0x5d, 0xb4, 0x9f, 0xec, 0xd9, 0xed, 0x5f,
	0xd6, 0x19, 0x14, 0x0b, 0x6c, 0xb0, 0xc3, 0x83, 0xc3, 0x67, 0x50, 0xbc, 0xd2, 0x6e, 0x0e, 0xbd,
	0xf1, 0x9e, 0xd3, 0x7f, 0xb8, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x34, 0x65, 0x16, 0x73, 0x3c,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PerService service

type PerServiceClient interface {
	AddPer(ctx context.Context, in *PerParams, opts ...client.CallOption) (*Response, error)
	GetPer(ctx context.Context, in *PerPn, opts ...client.CallOption) (*Response, error)
	DeletePer(ctx context.Context, in *PerParams, opts ...client.CallOption) (*Response, error)
	UpdatePer(ctx context.Context, in *PerParams, opts ...client.CallOption) (*Response, error)
}

type perServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPerServiceClient(serviceName string, c client.Client) PerServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "admin"
	}
	return &perServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *perServiceClient) AddPer(ctx context.Context, in *PerParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PerService.AddPer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perServiceClient) GetPer(ctx context.Context, in *PerPn, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PerService.GetPer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perServiceClient) DeletePer(ctx context.Context, in *PerParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PerService.DeletePer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perServiceClient) UpdatePer(ctx context.Context, in *PerParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PerService.UpdatePer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PerService service

type PerServiceHandler interface {
	AddPer(context.Context, *PerParams, *Response) error
	GetPer(context.Context, *PerPn, *Response) error
	DeletePer(context.Context, *PerParams, *Response) error
	UpdatePer(context.Context, *PerParams, *Response) error
}

func RegisterPerServiceHandler(s server.Server, hdlr PerServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PerService{hdlr}, opts...))
}

type PerService struct {
	PerServiceHandler
}

func (h *PerService) AddPer(ctx context.Context, in *PerParams, out *Response) error {
	return h.PerServiceHandler.AddPer(ctx, in, out)
}

func (h *PerService) GetPer(ctx context.Context, in *PerPn, out *Response) error {
	return h.PerServiceHandler.GetPer(ctx, in, out)
}

func (h *PerService) DeletePer(ctx context.Context, in *PerParams, out *Response) error {
	return h.PerServiceHandler.DeletePer(ctx, in, out)
}

func (h *PerService) UpdatePer(ctx context.Context, in *PerParams, out *Response) error {
	return h.PerServiceHandler.UpdatePer(ctx, in, out)
}
