// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package user

import (
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

import (
	"github.com/micro/go-micro/client"
	"github.com/micro/go-micro/server"
	"golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//创建用户参数结构体
type UserParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	GroupId              string   `protobuf:"bytes,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserParams) Reset()         { *m = UserParams{} }
func (m *UserParams) String() string { return proto.CompactTextString(m) }
func (*UserParams) ProtoMessage()    {}
func (*UserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *UserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserParams.Unmarshal(m, b)
}
func (m *UserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserParams.Marshal(b, m, deterministic)
}
func (m *UserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserParams.Merge(m, src)
}
func (m *UserParams) XXX_Size() int {
	return xxx_messageInfo_UserParams.Size(m)
}
func (m *UserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UserParams.DiscardUnknown(m)
}

var xxx_messageInfo_UserParams proto.InternalMessageInfo

func (m *UserParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserParams) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *UserParams) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

//用户信息
type User struct {
	Uid                  string    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string    `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Pwd                  string    `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Phone                string    `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Img                  string    `protobuf:"bytes,8,opt,name=img,proto3" json:"img,omitempty"`
	CreateTime           time.Time `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           time.Time `protobuf:"bytes,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *User) GetCreateTime() *time.Time {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *time.Time {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UserParams)(nil), "UserParams")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x24, 0x6d, 0xd3, 0x8f, 0xd7, 0xa5, 0xb2, 0x3a, 0x58, 0x59, 0x28, 0x11, 0x43, 0x27, 0x07,
	0x95, 0x8d, 0x7f, 0x80, 0xd4, 0x01, 0x85, 0xc2, 0xee, 0x26, 0x0f, 0x63, 0xa9, 0x8e, 0x2d, 0x3b,
	0x81, 0x3f, 0xce, 0x0f, 0x40, 0x76, 0xea, 0xa6, 0x0b, 0x62, 0xbb, 0x7b, 0xba, 0xbb, 0xf7, 0x7c,
	0x86, 0x95, 0xb1, 0xba, 0xd5, 0x45, 0xe7, 0xd0, 0xb2, 0x00, 0xb3, 0x5b, 0xa1, 0xb5, 0x38, 0x61,
	0x11, 0xd8, 0xb1, 0xfb, 0x28, 0x5a, 0xa9, 0xd0, 0xb5, 0x5c, 0x99, 0x5e, 0x90, 0xef, 0x01, 0xde,
	0x1c, 0xda, 0x17, 0x6e, 0xb9, 0x72, 0x84, 0xc0, 0xa4, 0xe1, 0x0a, 0x69, 0xb2, 0x49, 0xb6, 0x8b,
	0x32, 0x60, 0xb2, 0x82, 0xb1, 0xf9, 0xae, 0xe9, 0x28, 0x8c, 0x3c, 0x24, 0x14, 0x66, 0xc2, 0xea,
	0xce, 0x3c, 0xd7, 0x74, 0x1c, 0xa6, 0x91, 0xe6, 0x3f, 0x09, 0x4c, 0x7c, 0x9c, 0x37, 0x75, 0xb2,
	0x3e, 0xe7, 0x78, 0x78, 0x89, 0x1e, 0x5d, 0x45, 0xaf, 0x21, 0x45, 0xc5, 0xe5, 0xe9, 0x1c, 0xd3,
	0x93, 0xb8, 0x70, 0x32, 0x2c, 0x5c, 0x43, 0x6a, 0x3e, 0x75, 0x83, 0x34, 0xed, 0x75, 0x81, 0x78,
	0x9d, 0x54, 0x82, 0xce, 0x7b, 0x9d, 0x54, 0x82, 0x3c, 0x01, 0x54, 0x16, 0x79, 0x8b, 0x07, 0xa9,
	0x90, 0x4e, 0x37, 0xc9, 0x76, 0xb9, 0xcb, 0x58, 0x5f, 0x01, 0x8b, 0x15, 0xb0, 0x43, 0xac, 0xa0,
	0xbc, 0x52, 0x7b, 0x6f, 0x67, 0xea, 0xe8, 0x9d, 0xfd, 0xef, 0x1d, 0xd4, 0xf9, 0x03, 0xcc, 0x4b,
	0x74, 0x46, 0x37, 0x0e, 0xfd, 0x3b, 0x2b, 0x5d, 0x5f, 0x2a, 0xf4, 0xd8, 0x5f, 0xaa, 0x9c, 0x88,
	0x15, 0x2a, 0x27, 0x76, 0xef, 0xb0, 0xf4, 0x3d, 0xbd, 0xa2, 0xfd, 0x92, 0x15, 0x92, 0x7b, 0x1f,
	0x20, 0xa4, 0x6b, 0xd1, 0x92, 0x25, 0x1b, 0x3e, 0x24, 0x5b, 0xb0, 0x18, 0x9c, 0xdf, 0x90, 0x3b,
	0x48, 0xf7, 0x5a, 0xc8, 0xe6, 0x6f, 0xc9, 0x71, 0x1a, 0x2e, 0x7d, 0xfc, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x90, 0x79, 0x95, 0x85, 0x0a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	Register(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error)
	Login(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "userservice"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) Register(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Register", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *UserParams, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Login", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Register(context.Context, *UserParams, *Response) error
	Login(context.Context, *UserParams, *Response) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) Register(ctx context.Context, in *UserParams, out *Response) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *UserService) Login(ctx context.Context, in *UserParams, out *Response) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}
